name: IsekaiAuctions
main: me.verschuls.isekaiauctions.IsekaiAuctions

authors: [Verschuls, SedatTR]
version: 3.8
api-version: 1.13
folia-supported: true

description: The best, cheap, advanced, fully customizable auction plugin; like popular server!
softdepend:
  - Vault
  - CoinsEngine
  - HeadDatabase
  - PlaceholderAPI
  - PlayerPoints
  - TokenManager
  - Lands
  - UltraEconomy
  - LiteBans
  - AdvancedBan
  - DeluxeAuctionsDisplay
loadbefore:
  - DeluxeAuctionsDisplay
  - CMI

commands:
  auction:
    description: Default auction command.
    aliases: [deluxeauctions, ah, auc]
  auctionadmin:
    description: Default auction admin command.
    aliases: [deluxeauctionsadmin, ahadmin, aucadmin]