name: IsekaiAuctions
main: me.verschuls.isekaiauctions.IsekaiAuctions
authors: [Verschuls, SedatTR]
website: https://verschuls.xyz
version: "${version}"
api-version: 1.13
folia-supported: true
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.5.4
description: Aimed to improve performance and stability of the original DeluxeAuctions plugin.
softdepend:
  - Vault
  - CoinsEngine
  - HeadDatabase
  - PlaceholderAPI
  - PlayerPoints
  - TokenManager
  - Lands
  - UltraEconomy
  - LiteBans
  - AdvancedBan
  - DeluxeAuctionsDisplay
loadbefore:
  - DeluxeAuctionsDisplay
  - CMI

permissions:
  isekaiauctions.*:
    description: Gives access to all IsekaiAuction Permissions
    children:
      isekaiauctions.bypass.*: true
      isekaiauctions.commands.*: true
      isekaiauctions.commands.admin.*: true
      isekaiauctions.search: true
  isekaiauctions.bypass.*:
    description: Bypass everything in IsekaiAuctions
    children:
      isekaiauctions.bypass.creation: true
      isekaiauctions.bypass.cooldown: true
  isekaiauctions.item:
    description: idk
  isekaiauctions.category:
    description: idk
  isekaiauctions.search:
    description: Search option
  isekaiauctions.commands.admin.*:
    description: Gives access to all IA Admin Commands
    children:
      isekaiauctions.commands.admin: true
      isekaiauctions.commands.admin.cancel: true
      isekaiauctions.commands.admin.lock: true
      isekaiauctions.commands.admin.menu: true
      isekaiauctions.commands.admin.reload: true
      isekaiauctions.commands.admin.status: true
  isekaiauctions.commands.*:
    description: Gives access to all IA Player Commands
    children:
      isekaiauctions.commands.auctions: true
      isekaiauctions.commands.sell: true
      isekaiauctions.commands.view: true
      isekaiauctions.commands.bids: true
      isekaiauctions.commands.manage: true